module.exports = {
  teacher: 'Lärare',
  exampleTeacher: 'Jens Wadenius',
  group: 'Grupp',
  groupData: [
    { text: 'Åk 1', value: 1},
    { text: 'Åk 2', value: 2},
    { text: 'Åk 3', value: 3},
    { text: 'Åk 4', value: 4},
  ],
  student: 'Elev',
  studentData: [
    { text: 'Mikael Danielsson'},
    { text: 'Johanna Wadenius'},
    { text: 'Bobo Wadenius'},
    { text: 'Jens Wadenius'},
    { text: 'Lisa Danielsson'},
    { text: 'Ole Danielsson'},
    { text: 'Miro Danielsson'},
    { text: 'Mikael Danielsson'},
    { text: 'Johanna Wadenius'},
    { text: 'Bobo Wadenius'},
    { text: 'Jens Wadenius'},
    { text: 'Lisa Danielsson'},
    { text: 'Ole Danielsson'},
    { text: 'Miro Danielsson'},
    { text: 'Mikael Danielsson'},
    { text: 'Johanna Wadenius'},
    { text: 'Bobo Wadenius'},
    { text: 'Jens Wadenius'},
    { text: 'Lisa Danielsson'},
    { text: 'Ole Danielsson'},
    { text: 'Miro Danielsson'},
  ],
  material: 'Material',
  materialData: [
    { text: 'Läsning', value: 1},
    { text: 'Skrivning', value: 2},
    { text: 'Matte', value: 3},
  ],
  buttons: {
    newGroup: 'Lägg till ny grupp',
    newStudent: 'Lägg till ny elev',
    newMaterial: 'Lägg till nytt material',
    viewStudent: 'Elevvy',
    viewStudentMatrixes: 'Elevmatriser',
    viewGroupMatrixes: 'Gruppmatriser',
    printMaterial: 'Material for utskrift',
    logout: 'Logga ut'
  }
}